version: "3"
services:
  whisper:
    hostname: whisper
    build:
      context: ./whisper
      dockerfile: Dockerfile
    volumes:
      - ./in:/var/tmp/in
      - ./out:/var/tmp/out
    restart: always
    tty: true
